---

- name: Encrypt image file using Blowfish
  hosts: localhost
  gather_facts: false
  vars:
    file_to_encrypt: "/home/rouj/encryption-decryption/to_encrypt/xray.pdf"
    encrypted_file: "/home/rouj/encryption-decryption/encrypted/encrypted1.txt"
    blowfish_password: "admin123!"

  tasks:
    - name: Encrypt image using Blowfish
      become: yes
      command: openssl enc -e -blowfish -pbkdf2 -in "{{ file_to_encrypt }}" -out "{{ encrypted_file }}" -k "{{ blowfish_password }}"

    - name: Ensure encrypted file is present
      copy:
        src: "{{ encrypted_file }}"
        dest: "{{ encrpyted_file }}"
